version: '3.7'
services:
  javaservice:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: javaservice

    environment:
      - SPRING_PROFILES_ACTIVE=test

    ports:
      - 8130:8080

    volumes:
      - ~/docker/data/javappp/logs:/app/logs
      - ~/docker/data/javappp/temp:/app/tmp
